services:
  db-test-postgres:
    image: db-test-postgres:1.0
    container_name: db-test-postgres
    build:
      context: .
      dockerfile: ./docker/postgres-test/Dockerfile
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - "${HOST_DB_TEST_PORT}:5432"